[build]
command = "hugo"
publish = "public"

[build.environment]
HUGO_VERSION = "0.110.0"

[[redirects]]
from = "/*"
to = "https://commandline.ninja/:splat"
status = 301
force = true
conditions = { Domain = ["networkadm.in", "www.networkadm.in"] }


[[redirects]]
from = "/find-inactive-user-accounts-in-your-domain"
to = "/find-inactive-user-accts"

[[redirects]]
from = "use-powershell-to-find-windows-svcs-configured-to-run-as-another-user"
to = "/use-powershell-to-find-services-configured-to-run-as-another-user"

[[redirects]]
from = "/get-aduser-syntax-and-examples-post-refresh"
to = "/get-aduser-syantax-and-examples"

[[redirects]]
from = "/get-aduser-syantax-and-examples"
to = "/get-aduser-syntax-and-examples"

[[redirects]]
from = "/select-string-powershell7"
to = "select-string-whats-new"

[[redirects]]
from = "/tag/*"
to = "/tags"

[[redirects]]
from = "/easily-display-powershell-console-colors"
to = "/display-console-colors"

[[redirects]]
from = "/jumpstart-learning-resources-for-powershell/"
to = "/powershell-learning-resources/"

[[redirects]]
from = "/psindex"
to = "/tags"

[[redirects]]
from = "/:context/amp"
to = "/:context"
