[build]
command = "hugo"
publish = "public"

[build.environment]
HUGO_VERSION = "0.110.0"

# Force HTTPS
[[redirects]]
from = "http://networkadm.in/*"
to = "https://networkadm.in/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.networkadm.in/*"
to = "https://www.networkadm.in/:splat"
status = 301
force = true

# Redirect to new domain (HTTPS)
[[redirects]]
from = "https://networkadm.in/*"
to = "https://commandline.ninja/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.networkadm.in/*"
to = "https://commandline.ninja/:splat"
status = 301
force = true

[[redirects]]
from = "/find-inactive-user-accounts-in-your-domain"
to = "/find-inactive-user-accts"
status = 301
force = true


[[redirects]]
from = "/use-powershell-to-find-windows-svcs-configured-to-run-as-another-user"
to = "/use-powershell-to-find-services-configured-to-run-as-another-user"
status = 301
force = true


[[redirects]]
from = "/get-aduser-syntax-and-examples/"
to = "/get-aduser/"
status = 301
force = true

[[redirects]]
from = "/get-aduser-syntax-and-examples-refresh"
to = "/get-aduser/"
status = 301
force = true

[[redirects]]
from = "/get-aduser-syantax-and-examples"
to = "/get-aduser/"
status = 301
force = true

[[redirects]]
from = "/select-string-powershell7"
to = "/select-string-whats-new"
status = 301
force = true


[[redirects]]
from = "/tag/*"
to = "/tags"
status = 301
force = true

[[redirects]]
from = "/easily-display-powershell-console-colors"
to = "/display-console-colors"
status = 301
force = true

[[redirects]]
from = "/jumpstart-learning-resources-for-powershell/"
to = "/powershell-learning-resources/"
status = 301
force = true

[[redirects]]
from = "/psindex"
to = "/tags"

[[redirects]]
from = "/:context/amp"
to = "/:context"
